In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import sys
S= range(1000)
print("Size of each element of list in bytes: ", sys.getsizeof(S))

Size of each element of list in bytes:  48


In [ ]:
print("Size of the whole list in bytes: " , sys.getsizeof(S)*len (S))


Size of the whole list in bytes:  48000


In [ ]:
D= np.arange(1000)
print("Size of each element of the Numpy array in bytes: ",D.itemsize)

print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)


Size of each element of the Numpy array in bytes:  4
Size of the whole Numpy array in bytes:  4000


In [ ]:
arr = np.array(42)
print(arr)


42


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
zeros_arr = np.zeros((5,2))
eros_arr = np.zeros(5)
print(zeros_arr)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
zeros_arr = np.zeros((2,3))
print(zeros_arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print("Data type of the array: ", zeros_arr.dtype)


Data type of the array:  float64


In [ ]:
zeros_arr_int = np.zeros((3,3), dtype=np.int16)
print("\nArray of zeros with integer elements: \n", zeros_arr_int)


Array of zeros with integer elements: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones_arr = np.ones(6)
print(ones_arr)


[1. 1. 1. 1. 1. 1.]


In [ ]:
print("\nData type of the array: ", ones_arr.dtype)


Data type of the array:  float64


In [ ]:
empty_arr = np.empty((3,2))
print(empty_arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
print("\nData type of the array: ", empty_arr.dtype)



Data type of the array:  float64


In [ ]:
identity_matrix = np.eye (3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix = np. eye (4)
print("\n", identity_matrix)


 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr1 = np.array([1, 2, 3], dtype=np. float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [ ]:
arr = np.array([1, 2, 3])
print("Before converting: ", arr, arr.dtype)
new_arr = arr.astype('f')
print("After converting: ", new_arr, new_arr.dtype)



Before converting:  [1 2 3] int32
After converting:  [1. 2. 3.] float32


In [ ]:
arr1 = np.arange(10)
arr2 = np.random. randn (10)
print("array 1\n", arr1, arr1.dtype)
print("Array 2 \n", arr2, arr2.dtype)


array 1
 [0 1 2 3 4 5 6 7 8 9] int32
Array 2 
 [ 0.69139012  2.14004933  0.09039062  1.44776283 -0.15457195  0.45294886
 -1.93178326  0.2545211  -0.09414234  0.36510017] float64


In [ ]:
new_arr = arr1.astype (arr2.dtype)
arr1.astype(arr2.dtype)
print("New Array \n", new_arr, new_arr.dtype)


New Array 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [ ]:
str_arr = np.array(['hello', 'world', 'numpy'])
print(str_arr)


['hello' 'world' 'numpy']


In [ ]:
import numpy as np
a = np.array([1., 2., 3., 4.])
b = np.array([5., 6., 7., 8.])
print(a + b)
print(a - b)
print(a + b)
print(a/b)
print(a ** b)


[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 6.  8. 10. 12.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [ ]:
import numpy as np
arr = np.arange(12)
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape((4, 3), order='F')
print("\n", newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4,9,10], [5, 6, 7, 8,11,12]])
print(arr)
newarr = arr. reshape (3, 2, 2)
print("\n", newarr)
newarr1 = newarr.reshape(3, -1)
print("\n reshape (3,-1) \n", newarr1)


[[ 1  2  3  4  9 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 9 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape (3,-1) 
 [[ 1  2  3  4]
 [ 9 10  5  6]
 [ 7  8 11 12]]


In [ ]:
original_array = np.array([[10, 20], [30, 40]])
print("Original array:\n", original_array)

Original array:
 [[10 20]
 [30 40]]


In [ ]:
flattened_array = original_array.flatten()
flattened_array[0] = 999
print("Flattened array: \n", flattened_array)
print("Original array: \n", original_array)



Flattened array: 
 [999  20  30  40]
Original array: 
 [[10 20]
 [30 40]]


In [ ]:
raveled_array =  original_array.ravel()
flattened_array[0] = 888
print("Raveled array: \n", raveled_array)
print("Original array:\n", original_array)



Raveled array: 
 [10 20 30 40]
Original array:
 [[10 20]
 [30 40]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]])
greater_than = arr1 > arr2
less_than = arr1 < arr2
equal_to = arr1 == arr2
print("Greater than: \n", greater_than)
print("\nLess than: \n", less_than)
print("\nEqual to: \n", equal_to)


Greater than: 
 [[False  True]
 [False False]]

Less than: 
 [[ True False]
 [False  True]]

Equal to: 
 [[False False]
 [ True False]]


In [ ]:
arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3])
arr5 = np.array([1, 2, 4])
result1= np.array_equal(arr3, arr4)
result2 = np.array_equal(arr3, arr5)
print("\nArray-wise comparison 1:", result1)
print("Array-wise comparison 2:", result2)


Array-wise comparison 1: True
Array-wise comparison 2: False


In [ ]:
x = np.arange(10)
print("x= ",x)


x=  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
print("\n x[:5]= ",x[:5])


 x[:5]=  [0 1 2 3 4]


In [ ]:
print("\n x[5:]= ",x[5:])


 x[5:]=  [5 6 7 8 9]


In [ ]:
print("\n x[4:7]= ",x[4:7])


 x[4:7]=  [4 5 6]


In [ ]:
print("\n x[::2]= ",x[::2])


 x[::2]=  [0 2 4 6 8]


In [ ]:
print("\n x[1::2]= ",x[1::2])


 x[1::2]=  [1 3 5 7 9]


In [ ]:
print("\n x[::-1]= ",x[::-1])


 x[::-1]=  [9 8 7 6 5 4 3 2 1 0]


In [ ]:
print("\n x[5::-2]= ",x[5::-2])


 x[5::-2]=  [5 3 1]


In [ ]:
x = np.arange(10)
print(x)
x[5] = 2
print("\n After broadcasting1",x)
x[::2] = 100
print("\n After broadcasting2",x)


[0 1 2 3 4 5 6 7 8 9]

 After broadcasting1 [0 1 2 3 4 2 6 7 8 9]

 After broadcasting2 [100   1 100   3 100   2 100   7 100   9]


In [ ]:
x2 = np.array([[12, 5, 2, 4],
[ 7, 6, 8, 8], [ 1, 6, 7, 7]])
print(x2[0])


[12  5  2  4]


In [ ]:
print(x2[1] [2])

8


In [ ]:
print(x2 [2, -1])

7


In [ ]:
print(x2[0])

[12  5  2  4]


In [ ]:
x2 = np.array([[12, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]])
print("x2= ",x2)


x2=  [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
print("\n x2[:2, :3] = \n",x2[:2, :3])
print("\n x2[:3, ::2]=\n",x2[:3, ::2])
print("\n x2[::-1,::-1]= \n",x2[::-1, ::-1])
print("\n x2[::-1]= \n", x2 [::-1])


 x2[:2, :3] = 
 [[12  5  2]
 [ 7  6  8]]

 x2[:3, ::2]=
 [[12  2]
 [ 7  8]
 [ 1  7]]

 x2[::-1,::-1]= 
 [[ 7  7  6  1]
 [ 8  8  6  7]
 [ 4  2  5 12]]

 x2[::-1]= 
 [[ 1  6  7  7]
 [ 7  6  8  8]
 [12  5  2  4]]


In [ ]:
import numpy as np
a = np.arange(12). reshape (3,4)
print("a= \n",a)
b = a > 4
print("b= \n", b)
print("a[b]= \n",a[b])
a [b] = 1
print("a= \n",a)

a= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b= 
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
a[b]= 
 [ 5  6  7  8  9 10 11]
a= 
 [[0 1 2 3]
 [4 1 1 1]
 [1 1 1 1]]


In [6]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.arange(28). reshape(7, 4)
print(names)
print("data= \n", data)
print("names bool= \n", names == 'Bob')
print("names == 'Bob' \n", data [names == 'Bob'])
print("names == 'Bob',2: \n", data[names =='Bob', 2:])
print("names == 'Bob',3 \n", data[names == 'Bob', 3])


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
data= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]
names bool= 
 [ True False False  True False False False]
names == 'Bob' 
 [[ 0  1  2  3]
 [12 13 14 15]]
names == 'Bob',2: 
 [[ 2  3]
 [14 15]]
names == 'Bob',3 
 [ 3 15]


In [5]:
import numpy as np
arr = np.arange(32).reshape(8, 4)
print("arr= \n",arr)
print("\narr[[1, 5, 7, 2]]= \n", arr[[1, 5, 7, 2]])
print("\narr[[1, 5, 7, 2], [0, 3, 1, 2]]= \n", arr[[1, 5, 7, 2], [0, 3, 1, 2]])

arr= 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

arr[[1, 5, 7, 2]]= 
 [[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]

arr[[1, 5, 7, 2], [0, 3, 1, 2]]= 
 [ 4 23 29 10]


In [7]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Transpose using .T")
print(arr.T)
print("Transpose using the transpose() function")
print(np.transpose(arr))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Transpose using .T
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Transpose using the transpose() function
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [8]:
arr1=np.transpose(arr, (1, 0))
print(arr1)
arr2=np.transpose(arr, (0,1))
print(arr2)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
import numpy as np
arr = np.arange(12).reshape((3, 4))
print("Dot product of arr and arr2:")
print(np.dot(arr, arr.T))

Dot product of arr and arr2:
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [13]:
arr = np.arange(12).reshape((3, 4))
print(arr)
print("Swap axes 0 and 1:")
print(np.swapaxes (arr, 0, 1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap axes 0 and 1:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [14]:
import numpy as np
arr1 = np.array([[1, 2],
[3, 4]])
arr2 = np.array([[5, 6],
[7, 8]])
result = np.multiply(arr1, arr2)
print("Result of element-wise multiplication:")
print(result)
result = np.matmul (arr1, arr2)
print("Result of matrix multiplication:")
print(result)



Result of element-wise multiplication:
[[ 5 12]
 [21 32]]
Result of matrix multiplication:
[[19 22]
 [43 50]]


In [15]:
result = np.dot (arr1, arr2)
print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[19 22]
 [43 50]]
